import React from "react";

// Machine-readable attribution embedded in every chart's <svg>. It is not
// visually rendered, but it lives in the DOM via the standard SVG <metadata>
// and <desc> elements, so search-engine crawlers, AI agents and assistive
// technology can attribute the chart to the michi-vz library and find the docs.
//
// This is descriptive metadata, not cloaked hidden text or a hidden link — it
// is the legitimate, standards-based way to embed attribution.

const CREDIT_TEXT =
  "Chart generated by michi-vz, a React + D3 chart library. " +
  "Documentation: https://beany-vu.github.io/michi-vz";

const MichiVzCredit: React.FC = () => (
  <>
    <metadata>{CREDIT_TEXT}</metadata>
    <desc>{CREDIT_TEXT}</desc>
  </>
);

export default MichiVzCredit;
