import React, {
  useMemo,
  useRef,
  useState,
  useLayoutEffect,
  useCallback,
  useEffect,
} from "react";
import * as d3 from "d3";
import isEqual from "lodash/isEqual";
import Title from "./shared/Title";
import YaxisLinear from "./shared/YaxisLinear";
import XaxisLinear from "./shared/XaxisLinear";
import LoadingIndicator from "./shared/LoadingIndicator";
import { DEFAULT_COLORS } from "./shared/colors";
import { useDisplayIsNodata } from "./hooks/useDisplayIsNodata";
import useDeepCompareEffect from "use-deep-compare-effect";
import styled from "styled-components";
import { sanitizeForClassName } from "./hooks/lineChart/lineChartUtils";
import TooltipHint from "src/components/shared/TooltipHint";
import { XaxisDataType } from "src/types/data";

const AreaChartContainer = styled.div`
  position: relative;
  path {
    transition: opacity 0.05s ease-out;
    will-change: opacity;
  }
  .tooltip {
    pointer-events: none;
    will-change: transform;
  }
  .hover-line {
    pointer-events: none;
  }
`;

interface DataPoint {
  date: number;
  [key: string]: number | undefined;
}

interface AreaDataPoint {
  0: number;
  1: number;
  data: DataPoint;
}

interface ChartMetadata {
  xAxisDomain: string[];
  yAxisDomain: [number, number];
  visibleItems: string[];
  renderedData: { [key: string]: DataPoint[] };
  chartType: "area-chart";
  legendData?: { label: string; color: string; order: number; disabled?: boolean }[];
}

interface Props {
  series: DataPoint[];
  keys: string[];
  width: number;
  height: number;
  margin: { top: number; right: number; bottom: number; left: number };
  title?: string;
  xAxisFormat?: (d: number) => string;
  yAxisFormat?: (d: number) => string;
  yAxisDomain?: [number, number] | null;
  tooltipFormatter?: (d: DataPoint, series: DataPoint[], key: string) => string | null;
  children?: React.ReactNode;
  xAxisDataType: XaxisDataType;
  isLoading?: boolean;
  isLoadingComponent?: React.ReactNode;
  isNodataComponent?: React.ReactNode;
  isNodata?: boolean | ((dataSet: DataPoint[]) => boolean);
  onChartDataProcessed?: (metadata: ChartMetadata) => void;
  onHighlightItem?: (labels: string[]) => void;
  filter?: { date: number; sortingDir: "asc" | "desc" };
  ticks?: number;
  // colors is the color palette for the chart for new generated colors
  colors?: string[];
  // colorsMapping is the color mapping for the chart for existing colors
  // the purpose is to share the same color mapping between charts
  colorsMapping?: { [key: string]: string };
  onColorMappingGenerated?: (colorsMapping: { [key: string]: string }) => void;
  // highlightItems and disabledItems as props for better performance
  highlightItems?: string[];
  disabledItems?: string[];
  /**
   * Force Y axis to always show 0-100% range regardless of data values.
   * - When true: Y axis is fixed at [0, 100], even if data exceeds 100%
   * - When false (default): Y axis shows [0, 100] minimum, but extends higher if data exceeds 100%
   * Useful for percentage-based charts where you always want to show the full 0-100% scale.
   */
  forcePercentageScale?: boolean;
}

const MARGIN = { top: 50, right: 50, bottom: 50, left: 50 };
const WIDTH = 900;
const HEIGHT = 480;

const AreaChart: React.FC<Props> = ({
  series,
  width = WIDTH,
  height = HEIGHT,
  margin = MARGIN,
  title,
  keys,
  xAxisFormat,
  yAxisFormat,
  yAxisDomain = null,
  tooltipFormatter = null,
  xAxisDataType = "number",
  children,
  isLoading = false,
  isLoadingComponent,
  isNodataComponent,
  isNodata,
  onChartDataProcessed,
  onHighlightItem,
  filter,
  ticks = 5,
  colors = DEFAULT_COLORS,
  colorsMapping = {},
  onColorMappingGenerated,
  highlightItems = [],
  disabledItems = [],
  forcePercentageScale = false,
}) => {
  const ref = useRef<SVGSVGElement>(null);
  const [hoverInfo, setHoverInfo] = useState<{
    dataPoint: DataPoint;
    x: number;
    areaKey: string;
  } | null>(null);
  const renderCompleteRef = useRef(false);
  const prevChartDataRef = useRef<ChartMetadata | null>(null);
  const [isTooltipSticky, setIsTooltipSticky] = useState(false);
  const [isTooltipVisible, setIsTooltipVisible] = useState(false);

  // Tooltip refs for direct DOM access (performance optimization)
  const tooltipRef = useRef<HTMLDivElement>(null);
  const tooltipContentRef = useRef<HTMLDivElement>(null);

  // Ref to track the last color mapping sent to prevent infinite loops
  const lastColorMappingSentRef = useRef<{ [key: string]: string }>({});

  // Memoize callback functions to prevent infinite loops
  const memoizedOnColorMappingGenerated = useCallback(
    (colorsMapping: { [key: string]: string }) => {
      if (onColorMappingGenerated) {
        onColorMappingGenerated(colorsMapping);
      }
    },
    [onColorMappingGenerated]
  );

  // Remove local generatedColorsMapping logic
  // Use colorsMapping (from props, generated by legend) for all color assignments

  // Notify parent about generated color mapping with infinite loop protection
  useLayoutEffect(() => {
    // This useLayoutEffect is no longer needed as color mapping is handled by props
  }, []);

  const xScale = useMemo(() => {
    if (xAxisDataType === "number") {
      return d3
        .scaleLinear()
        .domain([d3.min(series, d => d.date || 0), d3.max(series, d => d.date || 1)])
        .range([margin.left, width - margin.right])
        .clamp(true)
        .nice();
    }

    const minDate = d3.min(
      series.map(d => new Date(xAxisDataType === "date_annual" ? `${d.date} 01 01` : d.date))
    );
    const maxDate = d3.max(series.map(d => new Date(d.date)));

    return d3
      .scaleTime()
      .domain([minDate || 0, maxDate || 1])
      .range([MARGIN.left, width - margin.right]);
    // .nice();
  }, [series, width, height, disabledItems, xAxisDataType]);

  // yScale
  const yScaleDomain = useMemo(() => {
    // Force 0-100% scale if forcePercentageScale is enabled
    // This is useful when you want to always show the full percentage range
    // even if data values exceed 100%
    if (forcePercentageScale) {
      return [0, 100];
    }

    if (yAxisDomain) {
      return yAxisDomain;
    }

    // Calculate the max stacked sum across all data points
    // Only sum the keys that are currently active (not disabled)
    const maxStackedSum = d3.max(
      series,
      d =>
        d3.sum(
          keys.map(key => {
            const val = d[key];
            return val != null && !isNaN(val as number) ? (val as number) : 0;
          })
        ) || 0
    ) || 0;

    // Minimum domain is [0, 100] for percentage charts, but extend if data exceeds 100
    return [0, Math.max(100, maxStackedSum)];
  }, [series, keys, yAxisDomain, forcePercentageScale]);

  const yScale = useMemo(
    () => {
      const scale = d3
        .scaleLinear()
        .domain(yScaleDomain)
        .range([height - margin.bottom, margin.top])
        .clamp(true);

      // Only apply .nice() when not forcing percentage scale
      // .nice() extends domain to "nicer" round numbers which we don't want when forcing 100%
      return forcePercentageScale ? scale : scale.nice();
    },
    [yScaleDomain, height, margin, forcePercentageScale]
  );

  const stackedData = useMemo(() => {
    return d3.stack<DataPoint, string>().keys(keys)(series);
  }, [series, keys]);

  // Memoized area data to avoid recreating on every render
  const areaData = useMemo(() => {
    return stackedData.map((keyData, index) => ({
      key: keys[index],
      values: keyData,
      fill: colorsMapping[keys[index]] || colors[index % colors.length],
    }));
  }, [stackedData, keys, colorsMapping, colors]);

  // Helper to get date value for bisector comparison
  const getDateValue = useCallback(
    (d: DataPoint) => {
      if (xAxisDataType === "number") return d.date;
      return new Date(xAxisDataType === "date_annual" ? `${d.date} 01 01` : d.date).getTime();
    },
    [xAxisDataType]
  );

  // Bisector for finding nearest data point
  const bisect = useMemo(() => {
    return d3.bisector((d: DataPoint) => getDateValue(d)).left;
  }, [getDateValue]);

  // Find which area the mouse is over by Y position
  const findAreaAtPosition = useCallback(
    (mouseY: number, dataPoint: DataPoint): string | null => {
      // Get the stacked values for this data point for each key
      for (let i = areaData.length - 1; i >= 0; i--) {
        const area = areaData[i];
        const pointData = area.values.find(v => v.data.date === dataPoint.date);
        if (pointData) {
          const y0 = yScale(pointData[0] || 0);
          const y1 = yScale(pointData[1] || 0);
          if (mouseY >= y1 && mouseY <= y0) {
            return area.key;
          }
        }
      }
      // Return null if mouse is not over any area (e.g., white space when total < 100%)
      return null;
    },
    [areaData, yScale]
  );

  const areaGenerator = d3
    .area<AreaDataPoint>()
    .defined(() => true)
    .x(d => {
      if (xAxisDataType === "number") {
        return xScale(d.data.date);
      } else {
        // Assuming d.data.date is a JavaScript Date object
        return xScale(new Date(d.data.date).getTime());
      }
    })
    .y0(d => yScale(d[0] || 0))
    .y1(d => yScale(d[1] || 0))
    .curve(d3.curveMonotoneX);

  const handleAreaSegmentHover = useCallback(
    (dataPoint: DataPoint, key: string) => {
      if (tooltipFormatter) {
        return tooltipFormatter(dataPoint, series, key);
      }

      return `
        <div style="background: #fff; padding: 5px">
            <p>${dataPoint.date}</p>
            <p style="color:${colorsMapping[key]}">${key}: ${dataPoint[key] ?? "N/A"}</p>
        </div>`;
    },
    [tooltipFormatter, series, colorsMapping]
  );

  const displayIsNodata = useDisplayIsNodata({
    dataSet: series,
    isLoading: isLoading,
    isNodataComponent: isNodataComponent,
    isNodata: isNodata,
  });

  useLayoutEffect(() => {
    renderCompleteRef.current = true;
  }, []);

  useDeepCompareEffect(() => {
    if (renderCompleteRef.current && onChartDataProcessed) {
      // Get the domain from xScale
      let domain;
      if (xAxisDataType === "number") {
        domain = [d3.min(series, d => d.date || 0), d3.max(series, d => d.date || 1)];
      } else {
        // For date types, ensure unique dates
        domain = [...new Set(series.map(d => d.date))];
      }

      // Ensure yScaleDomain is always a tuple with 2 elements
      const safeYDomain: [number, number] =
        Array.isArray(yScaleDomain) && yScaleDomain.length === 2
          ? (yScaleDomain as [number, number])
          : [0, yScaleDomain[1] || 0];

      // Generate all keys from series data (including disabled items)
      const allKeys = Array.from(
        new Set(series.flatMap(d => Object.keys(d)).filter(key => key !== "date" && key !== "code"))
      );

      // Sort keys based on values at the filter date if filter exists
      let sortedKeys = allKeys;
      const sortValues: { [key: string]: number } = {};

      if (filter?.date) {
        // Calculate sort values for all keys (including disabled items)
        allKeys.forEach(key => {
          const value = series.find(d => String(d.date) === String(filter.date))?.[key] || 0;
          sortValues[key] = value;
        });

        sortedKeys = [...allKeys].sort((a, b) => {
          const aValue = sortValues[a];
          const bValue = sortValues[b];
          return filter.sortingDir === "desc" ? bValue - aValue : aValue - bValue;
        });
      }

      // Generate legend data with colors based on legend order
      const legendData = sortedKeys.map((key, index) => {
        // Use existing color from colorsMapping if available, otherwise assign new color
        let finalColor = colorsMapping[key];

        if (!finalColor) {
          // Assign colors based on legend order using DEFAULT_COLORS
          const colorIndex = index % colors.length;
          const baseColor = colors[colorIndex];

          // Calculate opacity for repeat items beyond color palette
          const repeatCycle = Math.floor(index / colors.length);
          const opacity = Math.max(0.1, 1 - repeatCycle * 0.1);

          // Create color with opacity if needed
          finalColor =
            repeatCycle > 0
              ? `${baseColor}${Math.round(opacity * 255)
                  .toString(16)
                  .padStart(2, "0")}`
              : baseColor;
        }

        return {
          label: key,
          color: finalColor,
          order: index,
          disabled: disabledItems.includes(key),
          dataLabelSafe: sanitizeForClassName(key),
          sortValue: sortValues[key],
        };
      });

      // Generate new color mapping based on legend order
      const newColorMapping: { [key: string]: string } = {};
      legendData.forEach(item => {
        newColorMapping[item.label] = item.color;
      });

      // Update color mapping if it has changed
      if (!isEqual(newColorMapping, lastColorMappingSentRef.current)) {
        lastColorMappingSentRef.current = { ...newColorMapping };
        memoizedOnColorMappingGenerated(newColorMapping);
      }

      const currentMetadata: ChartMetadata = {
        xAxisDomain: domain.map(String),
        yAxisDomain: safeYDomain,
        visibleItems: sortedKeys.filter(key => !disabledItems.includes(key)),
        renderedData: {
          [keys[0]]: series,
        },
        chartType: "area-chart",
        legendData: legendData,
      };

      // Check if data has actually changed
      const hasChanged =
        !prevChartDataRef.current ||
        JSON.stringify(prevChartDataRef.current.xAxisDomain) !==
          JSON.stringify(currentMetadata.xAxisDomain) ||
        JSON.stringify(prevChartDataRef.current.yAxisDomain) !==
          JSON.stringify(currentMetadata.yAxisDomain) ||
        JSON.stringify(prevChartDataRef.current.visibleItems) !==
          JSON.stringify(currentMetadata.visibleItems) ||
        JSON.stringify(Object.keys(prevChartDataRef.current.renderedData).sort()) !==
          JSON.stringify(Object.keys(currentMetadata.renderedData).sort());

      // Always update the ref with latest metadata
      prevChartDataRef.current = currentMetadata;

      // Only call callback if data has changed
      if (hasChanged) {
        onChartDataProcessed(currentMetadata);
      }
    }
  }, [series, xAxisDataType, yScaleDomain, keys, disabledItems, filter, onChartDataProcessed]);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (isTooltipSticky && tooltipRef.current) {
        const tooltipElement = (event.target as HTMLElement).closest(".tooltip");
        const chartElement = (event.target as HTMLElement).closest("svg.chart");

        // Only reset if click was OUTSIDE BOTH tooltip AND chart
        if (!tooltipElement && !chartElement) {
          setIsTooltipVisible(false);
          setIsTooltipSticky(false);
        }
      }
    };

    if (isTooltipSticky) {
      document.addEventListener("click", handleClickOutside);
      return () => {
        document.removeEventListener("click", handleClickOutside);
      };
    }
  }, [isTooltipSticky]);

  // Tooltip positioning using refs and CSS transform
  const repositionTooltip = useCallback(
    (event: React.MouseEvent, areaKey: string, dataPoint: DataPoint, forceReposition = false) => {
      // Skip repositioning if tooltip is sticky (pinned) unless force flag is set
      if (!forceReposition && isTooltipSticky) return;

      if (!tooltipRef.current || !tooltipContentRef.current) return;

      // Update content first
      tooltipContentRef.current.innerHTML = handleAreaSegmentHover(dataPoint, areaKey);

      // Get position
      const [x, y] = d3.pointer(event);

      // Update position
      const tooltipWidth = tooltipRef.current.offsetWidth;
      const tooltipHeight = tooltipRef.current.offsetHeight;

      setIsTooltipVisible(true);
      tooltipRef.current.style.transform = `translate(${x - tooltipWidth / 2}px, ${y - tooltipHeight - 10}px)`;
    },
    [handleAreaSegmentHover, isTooltipSticky]
  );

  // Handle mouse move with bisector to find nearest data point
  const handleChartMouseMove = useCallback(
    (event: React.MouseEvent) => {
      // Skip if tooltip is sticky (pinned) or no data
      if (isTooltipSticky || series.length === 0) return;

      const [mouseX, mouseY] = d3.pointer(event);

      // Convert pixel position to date value
      const x0 = xScale.invert(mouseX);
      const index = bisect(series, xAxisDataType === "number" ? (x0 as number) : (x0 as Date).getTime());

      // Get closest data point (compare distance to neighbors)
      const d0 = series[index - 1];
      const d1 = series[index];

      let dataPoint: DataPoint;
      if (!d0) {
        dataPoint = d1;
      } else if (!d1) {
        dataPoint = d0;
      } else {
        const x0Val = xAxisDataType === "number" ? (x0 as number) : (x0 as Date).getTime();
        dataPoint = x0Val - getDateValue(d0) > getDateValue(d1) - x0Val ? d1 : d0;
      }

      if (!dataPoint) return;

      // Find which area the mouse is over (by Y position)
      const areaKey = findAreaAtPosition(mouseY, dataPoint);

      // If mouse is in white space (no area), hide tooltip and clear hover
      if (!areaKey) {
        setIsTooltipVisible(false);
        setHoverInfo(null);
        onHighlightItem?.([]);
        return;
      }

      // Calculate x position for the vertical line
      const xPos = xScale(
        xAxisDataType === "number"
          ? dataPoint.date
          : new Date(xAxisDataType === "date_annual" ? `${dataPoint.date} 01 01` : dataPoint.date)
      );

      setHoverInfo({ dataPoint, x: xPos, areaKey });
      onHighlightItem?.([areaKey]);

      // Update tooltip
      repositionTooltip(event, areaKey, dataPoint);
    },
    [
      isTooltipSticky,
      series,
      xScale,
      bisect,
      xAxisDataType,
      getDateValue,
      findAreaAtPosition,
      onHighlightItem,
      repositionTooltip,
    ]
  );

  // Handle mouse out
  const handleChartMouseOut = useCallback(
    (event: React.MouseEvent) => {
      // Skip if tooltip is sticky (pinned)
      if (isTooltipSticky) return;

      const target = event.relatedTarget as HTMLElement;
      if (!target || !target.closest("svg.chart")) {
        setIsTooltipVisible(false);
        setHoverInfo(null);
        onHighlightItem?.([]);
      }
    },
    [isTooltipSticky, onHighlightItem]
  );

  // Handle click on chart
  const handleChartClick = useCallback(
    (event: React.MouseEvent) => {
      if (hoverInfo) {
        // Force reposition first to ensure tooltip content is set
        repositionTooltip(event, hoverInfo.areaKey, hoverInfo.dataPoint, true);
        // Then set sticky state - both states together
        setIsTooltipSticky(true);
        setIsTooltipVisible(true);
      }
    },
    [hoverInfo, repositionTooltip]
  );

  return (
    <AreaChartContainer>
      <div
        ref={tooltipRef}
        className={"tooltip"}
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          background: "white",
          padding: "5px",
          zIndex: 1000,
          visibility: isTooltipVisible ? "visible" : "hidden",
          pointerEvents: isTooltipSticky ? "auto" : "none",
        }}
      >
        <div ref={tooltipContentRef} className="tooltip-content" />
        {!isTooltipSticky && <TooltipHint />}
      </div>

      {/* Overlay when sticky - blocks mouse events on chart */}
      {isTooltipSticky && (
        <div
          className="tooltip-overlay"
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            width: "100%",
            height: "100%",
            background: "transparent",
            zIndex: 999,
            cursor: "pointer",
          }}
          onClick={() => {
            setIsTooltipSticky(false);
            setIsTooltipVisible(false);
            setHoverInfo(null);
          }}
        />
      )}

      <svg
        className={"chart"}
        ref={ref}
        width={width}
        height={height}
        style={{ overflow: "visible" }}
        onMouseMove={handleChartMouseMove}
        onMouseOut={handleChartMouseOut}
        onClick={handleChartClick}
      >
        {children}
        <Title x={width / 2} y={MARGIN.top / 2}>
          {title}
        </Title>
        {series.length > 0 && !isLoading && (
          <>
            <XaxisLinear
              xScale={xScale}
              height={height}
              margin={margin}
              xAxisFormat={xAxisFormat}
              xAxisDataType={xAxisDataType}
              ticks={ticks}
            />
            <YaxisLinear
              yScale={yScale}
              width={width}
              height={height}
              margin={margin}
              highlightZeroLine={true}
              yAxisFormat={yAxisFormat}
            />
          </>
        )}
        <g>
          {areaData.map(areaDataItem => (
            <path
              key={areaDataItem.key}
              d={areaGenerator(areaDataItem.values)}
              fill={areaDataItem.fill ? areaDataItem.fill : "#fdfdfd"}
              stroke={"#fff"}
              strokeWidth={1}
              opacity={
                highlightItems.length === 0 || highlightItems.includes(areaDataItem.key) ? 1 : 0.05
              }
              data-label={areaDataItem.key}
              data-label-safe={sanitizeForClassName(areaDataItem.key)}
              style={{ pointerEvents: "none" }}
            />
          ))}
          {/* Thin vertical lines per area to indicate which dates have data */}
          {areaData.map(areaDataItem =>
            areaDataItem.values.map(dataPoint => {
              const xPos = xScale(
                xAxisDataType === "number"
                  ? dataPoint.data.date
                  : new Date(dataPoint.data.date)
              );
              const y0 = yScale(dataPoint[0] || 0);
              const y1 = yScale(dataPoint[1] || 0);
              const segmentHeight = y0 - y1;
              // Only show indicator if segment has height (data exists)
              if (segmentHeight <= 0) return null;
              return (
                <line
                  key={`data-indicator-${areaDataItem.key}-${dataPoint.data.date}`}
                  className="data-indicator"
                  x1={xPos}
                  x2={xPos}
                  y1={y1}
                  y2={y0}
                  stroke="#ccc"
                  strokeWidth={1}
                  opacity={1}
                  pointerEvents="none"
                />
              );
            })
          )}
          {/* Vertical indicator line at hover position */}
          {hoverInfo && (
            <line
              className="hover-line"
              x1={hoverInfo.x}
              x2={hoverInfo.x}
              y1={margin.top}
              y2={height - margin.bottom}
              stroke="#666"
              strokeWidth={2}
              pointerEvents="none"
            />
          )}
        </g>
      </svg>
      {isLoading && isLoadingComponent && <>{isLoadingComponent}</>}
      {isLoading && !isLoadingComponent && <LoadingIndicator />}
      {displayIsNodata && <>{isNodataComponent}</>}
    </AreaChartContainer>
  );
};

export default AreaChart;
