import type { Meta, StoryObj } from "@storybook/react";
declare const meta: Meta;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const WithFilter: Story;
export declare const WithDifferentShapes: Story;
export declare const WithColorMapping: Story;
export declare const WithHighlightedItems: Story;
export declare const WithDisabledItems: Story;
export declare const Loading: Story;
export declare const NoData: Story;
export declare const CustomTooltip: Story;
export declare const TimeSeriesData: Story;